Refactor tag script to handle options and successive tags
pbstck/models pull request #12
Opened 2021-11-19 20:51 UTC by cforycki

## Why

A bug have been reported to me by Erwann, successive tags was adding additional `golang/` each time the script was run.
For example, we would have `golang/golang/v1.2.0` the second time

## Refactoring

I have not found a reliable way with git, to get the last tag for each case (could not get the last tag when multiple tags where pointing at the same commit). So I added a `VERSION` file at the root of the repository, to hold the current version number.

You can use different options:
* `--dry-run` to see which tags would have been created with the other options specified
* `--help` to print the help
* `--major` or `--minor` or `--patch` or `a version number` to bump the version

## Demo

![tag](https://user-images.githubusercontent.com/13793980/142689300-ffb847dc-1276-477e-bfb1-1644a210e5c7.png)

2021-11-19 21:10 UTC, cforycki commented on Makefile
> +	echo "Use ./script/tag.sh to make a new tag"
Could not find a way to pass down `make` arguments to the shell script ...

2021-11-22 08:03 UTC, MichaelBitard commented on Makefile
> +	echo "Use ./script/tag.sh to make a new tag"
`TOTO=true ./script/tag.sh`

2021-11-22 08:05 UTC, MichaelBitard requested changes
I don't agree with the VERSION file at the root, that means that we cannot tag anything we want, we have to add a (useless) commit before being able to tag.

There are multiple ways to retrieve the last tag with git, I'd say we should go with that instead

2021-11-22 08:09 UTC, cforycki commented on Makefile
> +	echo "Use ./script/tag.sh to make a new tag"
What I meant was to do something like `make tag --major` so that `--major` would be passed to the shell script.
If we have to parse the options twice it's not great :/
The only way I could think of was to add multiple target to handle most of if (`make tag_major`, `make tag_minor`, `make tag_patch`)

2021-11-22 08:13 UTC, MichaelBitard commented on Makefile
> +	echo "Use ./script/tag.sh to make a new tag"
That's not really beautiful indeed, but you can have something like that: https://stackoverflow.com/a/14061796

2021-11-22 08:15 UTC, cforycki commented
@MichaelBitard could not find a way to do it ... I've tried a lot of things with `git tag -l`, `git rev-list`, `git describe`, but there is always a case the "last tag" could not be retrieved

If we want to tag anything we want, we should be able to tag something twice, and for that case I can't find a way to do it with git commands only.

Maybe I went to far and we don't care about some cases :sweat_smile: 
But anyway yeah the VERSION file is ugly, I'll wait for other reviews for ideas, and I'll change the way it's done :)

2021-11-22 08:33 UTC, MichaelBitard commented
@cforycki If I remember correctly, at some point we had some scripts that created the changelog based on the last tags.

We still have some of these files somewhere: https://github.com/pbstck/aggregation-processings/blob/master/scripts/changelog

They do some shenanigan with the git tags.

We do not really care if it does not work in all cases IMHO, a 80-20 is fine by me ;)

2021-11-22 08:38 UTC, cforycki commented
@MichaelBitard Alright, I'll check it later, thanks !

TODO:
* Remove VERSION file
* Refactor script to use git commands to retrieve last tag

2021-11-22 15:02 UTC, slezier approved these changes

2021-11-30 09:14 UTC, cforycki commented
TG: remove VERSION, tag annotated, date as version number

2021-11-30 19:31 UTC, cforycki commented
Re-refactored, updated original post.

2021-12-02 08:49 UTC, vmaerten approved these changes

2021-12-08 08:03 UTC, slezier approved these changes

2021-12-09 08:56 UTC, sdeluce approved these changes

2021-12-09 16:01 UTC, merged